# Generated by Django 4.1.7 on 2023-03-24 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['create_at']},
        ),
    ]
